from pyrogram import filters
from pyrogram.types import Message
from AloneMusic import app
import random

# ===== YUXU YOZUMU (GENİŞ) =====
ruya_sozluk = {
    "su": "Hüzur, təmizlənmə və bərəkət mənasını verir.",
    "dəniz": "Həyatınızda böyük dəyişikliklərin yaxınlaşdığını göstərir.",
    "ilan": "Paxıl və ya gizli bir düşmənə işarə edə bilər.",
    "pul": "Maddi fürsətlər və ya yeni qazanc qapıları.",
    "uçmaq": "Azadlıq və hədəflərinə çatma arzusu.",
    "yıxılmaq": "Nəzarəti itirmək və ya narahatlıq yaşadığınızı göstərə bilər.",
    "ev": "Ailə və daxili hüzurla bağlı inkişaflar.",
    "körpə": "Yeni başlanğıclar və ümid.",
    "atəş": "Güclü duyğular və vacib dəyişiklik.",
    "ölmək": "Bir dövrün bağlanıb yeni bir dövrün başlaması.",
    "it": "Sadiq bir dost və ya dəstək.",
    "pişik": "İntuisiya və sirli durumlar.",
    "quş": "Azadlıq və xoş xəbər.",
    "maşın": "Həyatınızın yönünü dəyişdirəcək bir qərar.",
    "yol": "Yeni bir səfər və ya həyat dəyişikliyi.",
    "qızıl": "Böyük şans və dəyərli fürsətlər.",
    "yağış": "Arınma və emosional rahatlıq.",
    "qar": "Sakitlik, hüzur və ya gözləmə dövrü.",
    "ağac": "İnkişaf və kök salmaq.",
    "dağ": "Çətin amma dəyərli bir hədəf.",
    "bulud": "Başınızı qarışdıran düşüncələr və ya müvəqqəti qeyri-müəyyənlik.",
    "göyqurşağı": "Çətinliklərdən sonra gələcək xoşbəxtlik və ümid.",
    "mayak": "Sizə yol göstərəcək bir insan və ya vacib bir işarə.",
    "ada": "Tənha qalmaq istəyi və ya özünü kəşf etmə dövrü.",
    "qum": "Müvəqqəti vəziyyətlər və ya sürətlə dəyişən şərtl.",
    "səhra": "Səbr tələb edən çətin bir dövr.",
    "meşə": "Kəşf ediləcək yeni fürsətlər və bilinməyən yollar.",
    "mağara": "Daxili dünyanıza dönmə və gizli düşüncələrlə üzləşmə.",
    "qılınc": "Qəti bir qərar və ya mübarizə.",
    "qalxan": "Özünü qoruma ehtiyacı və ya müdafiə.",
    "zəncir": "Özünüzü məhdudlaşdırılmış hiss etdiyiniz bir vəziyyət.",
    "tac": "Uğur, hörmət və yüksəliş.",
    "taxt": "Güc və məsuliyyət sahibi olmaq.",
    "bayraq": "Uğur, qürur və hədəflərə çatmaq.",
    "hədiyyə": "Gözlənilməz xoş bir inkişaf.",
    "məktub": "Yaxınlarda alacağınız bir xəbər və ya mesaj.",
    "telefon": "Əlaqə saxlamalı olduğunuz vacib bir şəxs.",
    "pəncərə": "Yeni baxış bucaqları və fürsətlər.",
    "çp": "Sərhədlər qoyma və ya bir maneə ilə qarşılaşma.",
    "bağça": "Əmək verdiyiniz bir işin böyüməsi və inkişafı.",
    "toxum": "Gələcəkdə böyüyəcək yeni ideyalar və ya layihələr.",
    "fırtına": "Emosional qarışıqlıq və ya ani hadisələr.",
    "ildırım": "Ani fərqindəlik və ya gözlənilməz hadisə.",
    "gəmi": "Uzaq səfər və ya həyatınızda böyük bir dəyişiklik.",
    "liman": "Təhlükəsiz bir yerə çatma və hüzur tapmaq.",
    "qatar": "Planlı irəliləyən bir proses və ya taleyin yönləndirməsi.",
    "bilet": "Yeni bir fürsət və ya başlanğıc.",
    "xəritə": "Həyatınızda yön tapma və ya plan qurma.",
    "kompas": "Doğru yolu tapma və qərar vermə.",
    "kənd": "Sadəlik, hüzur və keçmişə həsrət.",
    "şəhər": "Sosial həyatın canlanması və yeni insanlarla tanışlıq.",
    "küçə": "Həyatınızda irəlilədiyiniz yol və qarşılaşacağınız fürsətlər.",
    "körpüdən keçmək": "Köhnə bir dövrü geridə qoyub yeni bir mərhələyə keçmək.",
    "kilid": "Hələ həll olunmamış bir məsələ və ya gizli bir vəziyyət.",
    "bıçaq": "Kəskin bir qərar vermə və ya bir münasibəti bitirmək.",
    "masa": "İclas, söhbət və ya vacib qərar prosesi.",
    "stul": "İstirahət ehtiyacı və ya qısa bir fasilə.",
    "bağlı qapı": "Hazırda əldə edə bilmədiyiniz bir fürsət.",
    "açıq qapı": "Yeni fürsətlər və başlanğıclar.",
    "işıq": "Həqiqətin üzə çıxması və fərqindəlik.",
    "qaranlıq": "Qeyri-müəyyənlik və ya bilinməyən vəziyyətlər.",
    "əl": "Kömək, dəstək və ya bir razılaşma.",
    "üz": "Bir şəxslə bağlı real duyğuların üzə çıxması.",
    "göz": "Diqqətli olmalı olduğunuz bir vəziyyət və ya intuisiya.",
    "gülmək": "Xoşbəxtlik və daxili hüzur.",
    "ağlamaq": "Emosional boşalma və rahatlama.",
    "qaçmaq": "Hədəflərinizə sürətlə yaxınlaşmaq.",
    "gizlənmək": "Bir vəziyyətdən qaçmaq istəyi.",
    "tutulmaq": "Bir həqiqətin üzə çıxması.",
    "itkin düşmək": "Həyatda yolunuzu axtardığınız bir dövr.",
    "tapmaq": "Uzun zamandır axtardığınız bir həlli kəşf etmək.",
    "üzmək": "Duyğularınızla bacarmaq və irəliləmək.",
    "boğulmaq": "Gərgin stress və ya təzyiq altında hiss etmək.",
    "qurtulmaq": "Çətin bir vəziyyətdən çıxış yolu tapmaq.",
    "yemək": "Ruhani və ya fiziki ehtiyacların qarşılanması.",
    "su içmək": "Rahatlama və enerji toplama.",
    "süfrə": "Ailə, birlik və paylaşmaq.",
    "qonaq": "Həyatınıza girəcək yeni bir şəxs.",
    "toy": "Böyük bir dəyişiklik və ya yeni başlanğıc.",
    "qəbir": "Keçmişdə qalan bir mövzu ilə üzləşmə.",
# Adlar (Azərbaycan adları və dağları)
  "anar": "Etibarlı, dürüst və ətrafı tərəfindən sevilən bir şəxsi təmsil edir.",
  "elvin": "Güclü xarakter, səbr və hörmət mənasını verir.",
  "əli": "Cəsarət, liderlik və güclü iradəni simvolizə edir.",
  "nicat": "Seçilmişlik, sayğınlıq və güclü şəxsiyyəti təmsil edir.",
  "tural": "Dostluq, səmimiyyət və daxili saflığı ifadə edir.",
  "vüsal": "Həyat enerjisi, sevgi və yaxın bağları simvolizə edir.",
  "ayxan": "Sürət, irəliləyiş və uğura çatma istəyini təmsil edir.",
  "babək": "Dürüstlük, cəsarət və etibarlılıq mənasını verir.",
  "kənan": "Səxavət, xeyirxahlıq və təmiz qəlbliliyi simvolizə edir.",
  "zaur": "Güclü iradə və liderlik xüsusiyyətlərini təmsil edir.",
  "polad": "Güc, qoruyuculuq və dözümlülük mənasını verir.",
  "nurlan": "Aydınlıq, nur və idarəetmə bacarığını simvolizə edir.",
  "yusif": "Səbr, gözəllik və xoş niyyəti təmsil edir.",
  "ibrahim": "Müdriklik, güvən və möhkəm xarakteri ifadə edir.",
  "ömər": "Ədalət, düzgünlük və güclü əxlaqi dəyərlər.",
  "həsən": "Xeyirxahlıq, mərhəmət və gözəl əxlaqı simvolizə edir.",
  "hüseyn": "Sədaqət, fədakarlıq və güclü bağlılıq.",
  "fuad": "Sakitlik, hüzur və tarazlı bir xarakter.",
  "fərid": "Barışıq, hüzur və dostluq mənasını verir.",
  "xəzər": "Azad ruh, geniş düşüncə və dəyişiklik.",
  "leyla": "Şəfqət, zəriflik və güclü ailə bağları.",
  "günay": "Səbr, mərhəmət və güclü ana fiquru.",
  "zeynəb": "Gözəllik, zəriflik və sevilən bir şəxsiyyət.",
  "fidan": "Saflıq, sadəlik və güclü xarakter.",
  "aytac": "Nazik davranışlar və zərif bir şəxsiyyəti simvolizə edir.",
  "aynur": "Xoşbəxtlik, sevinc və pozitiv enerji.",
  "nigar": "Sakitlik, hüzur və şəffaf düşüncələr.",
  "məleykə": "Şirinlik, sevgi və isti bir xarakter.",
  "arzu": "Gözəl xəbərlər və diqqət çəkən bir səs.",
  "lalə": "Sevimli, cazibədar və isti bir təbəssüm.",
  "nazrin": "Zəriflik, incəlik və həssas duyğular.",
  "banu": "Məğrur, güclü və sayğın bir xarakter.",
  "mədinə": "Sürətli düşünmə və güclü intuisiyalar.",
  "dilara": "Qəlbləri xoşbəxt edən, sevgi dolu şəxs.",
  "ayşən": "Zəriflik və səmimiyyət.",
  "aynurə": "Sirr dolu və maraq doğuran bir şəxsiyyət.",
  "nərmin": "Gözəllik və diqqət çəkən bir xarakter.",
  "sevda": "Reallıq, sadəlik və səmimiyyət.",
  "nəzrin": "Həyat enerjisi və canlılıq.",
  "dəniz": "Dərin duyğular və geniş bir baxış bucağı.",
  "mərcan": "Naziklik, yumşaqlıq və zəriflik.",
  "çiçək": "Sevgi, gözəllik və xoşbəxtlik.",
  "bahar": "Yenilik, bahar təravəti və ümid.",
  "sevgi": "Şəfqət, bağlılıq və güclü duyğular.",
  "ümid": "Yaxşı gələcəyə olan inam.",
  "namis": "Sayğınlıq, qürur və güclü xarakter.",
  "azad": "Müstəqillik və öz yolunu cızma istəyi.",
  "mərd": "Əxlaq, düzgünlük və yaxşı davranışlar.",
  "şahdağ": "Ucalıq, əzəmət və sarsılmaz iradəni təmsil edir.",
  "murovdağ": "Dözümlülük, çətinliklərə sinə gərmə və güc.",
  "bazardüzü": "Zirvədə olmaq, ən yüksək hədəflərə çatmaq.",
  "tufandağ": "Sərt xarakter amma möhkəm duruşu simvolizə edir.",
  "qapıçıq": "Mühafizəkar, sədaqətli və güclü bir kök.",
  "qoşqar": "Təbiiliyi, səmimiyyəti və ucalığı təmsil edir.",
  "🗣️": "gəl bir baxaq nə var nə yox",
  "adilə": "Ədalətli, mərhəmətli və etibarlı bir şəxsiyyət.",
  "afaq": "Təmizlik, saflıq və güclü xarakter.",
  "ayda": "Xoşbəxtlik və sevinc gətirən şəxs.",
  "sevinc": "Güclü və diqqətçəkən bir xarakter.",
  "almaz": "Parlaqlıq, enerji və canlılıq.",
  "təranə": "Dəyərli və xüsusi bir şəxs.",
  "alya": "Yüksək hədəflər və zərif bir xarakter.",
  "könül": "Gizem və isti bir şəxsiyyət.",
  "vəfa": "İstəklər, xəyallar və güclü duyğular.",
  "məsumə": "Şəfa, saflıq və xoş qəlblilik.",
  "tomris": "Güc, liderlik və cəsarət.",
  "asya": "Sirli, dərin düşüncəli bir xarakter.",
  "od": "Ehtiras, enerji və güclü duyğular.",
  "aybəniz": "Ay kimi parlaq və diqqətçəkən.",
  "aybükə": "Zərif və sayğın bir xarakter.",
  "aydan": "Aydınlıq, ümid və pozitiv enerji.",
  "ayfər": "Gözəllik və daxili hüzur.",
  "ayla": "Parlaqlıq və zəriflik.",
  "aynur": "Ay işığı kimi sakit və hüzurlu.",
  "aysel": "İşıq, ümid və pozitivlik.",
  "aysimə": "Ay kimi gözəl və diqqətçəkən.",
  "ayten": "Zərif və güclü bir xarakter.",
  "bahar": "Yenilik, ümid və təzələnmə.",
  "bəyim": "Sayğınlıq və güclü şəxsiyyət.",
  "bəlgə": "Açıq fikirli və net düşüncələr.",
  "bənövşə": "Gözəllik və diqqət çəkən bir xarakter.",
  "bərən": "Güclü və ağıllı bir şəxsiyyət.",
  "bəril": "Dəyərli və nadir bir xarakter.",
  "bəstə": "Harmoniya, sənət və yaradıcılıq.",
  "bətül": "Saflıq və güclü inanc.",
  "bəyaz": "Təmizlik, saflıq və məsumiyyət.",
  "bilgəhan": "Müdriklik və liderlik.",
  "bürcü": "Emosional dərinlik və intuisiya.",
  "canan": "Sevilən, dəyər verilən şəxs.",
  "ceyda": "Şən və enerjik xarakter.",
  "cəvahir": "Güclü və dözümlü bir şəxsiyyət.",
  "damla": "Saflıq, təbiilik və təravət.",
  "dəfnə": "Zəriflik, uğur və gözəllik.",
  "dəstə": "Birlik, harmoniya və bağlılıq.",
  "deniz": "Azadlıq və geniş düşüncə.",
  "diclə": "Güclü axın və dəyişiklik.",
  "dilan": "Sevgi və isti duyğular.",
  "duru": "Saflıq, sadəlik və şəffaflıq.",
  "əda nur": "Zəriflik və ruhani hüzur.",
  "ece nur": "Sayğınlıq və daxili hüzur.",
  "əda su": "Nazik və hüzur verən bir xarakter.",
  "ela": "Gözəllik, diqqətçəkicilik və zarafat."
}

# ===== FAL CAVABLARI (GENİŞ) =====
fal_listesi = [
"Bu gün şans səninlədir.",
"Yaxınlarda xoş bir xəbər alacaqsan.",
"Gözlədiyin bir mesaj gələ bilər.",
"Yeni bir fürsət qapını döyə bilər.",
"Qəlbini dinləsən, doğru yolu tapacaqsan.",
"Səbrli olmalı olduğun bir dövrdür.",
"Gözlənilməz bir tanışlıq ola bilər.",
"Həyatında kiçik amma vacib bir dəyişiklik var.",
"Köhnə bir dost yenidən həyatına girə bilər.",
"Yaxınlarda gözəl bir səyahət görünür.",
"Şansın xüsusilə axşam saatlarında artacaq.",
"Planlarını bir az təxirə salmalı ola bilərsən.",
"Sürpriz bir təklif ala bilərsən.",
"Yeni bir başlanğıc səni gözləyir.",
"Uzun zamandır düşündüyün bir məsələ aydınlaşacaq.",
"Həyatında yeni bir qapı açıla bilər.",
"Uzun zamandır gözlədiyin inkişaf yaxınlıqdadır.",
"Birindən gözəl bir dəstək görəcəksən.",
"Daxili səsin sənə doğru yolu göstərəcək.",
"Bu gün verdiyin qərar vacib ola bilər.",
"Şanslı bir qarşılaşma yaşaya bilərsən.",
"Həyatında yeni bir səhifə açılır.",
"Gözlənilməz bir fürsət yaxalaya bilərsən.",
"Yaxınlarda sevindirici bir hadisə var.",
"Uzun müddətdir düşündüyün plan reallaşa bilər.",
"Bir arzun çin olmağa çox yaxındır.",
"Bu gün pozitiv enerji səninlədir.",
"Bir dostun sənə vacib bir ideya verə bilər.",
"Həyatında gözəl bir dəyişiklik başlaya bilər.",
"Yeni bir mühit səni gözləyir.",
"Şanslı bir gün səni gözləyir.",
"Bu gün alacağın xəbər səni xoşbəxt edə bilər.",
"Yaxınlarda səni təəccübləndirəcək bir hadisə olacaq.",
"Gözlənilməz bir fürsət ortaya çıxa bilər.",
"Həyatında hüzurlu bir dövr başlaya bilər.",
"Yeni bir tanışlıq həyatına rəng qata bilər.",
"Bir arzun yaxında reallaşa bilər.",
"Yaxınlarda gözəl bir sürpriz yaşaya bilərsən.",
"Həyatında müsbət inkişaflar olacaq.",
"Səbrli olsan, istədiyin şeyə nail ola bilərsən.",
"Bu gün özünə güvənməli olduğun bir gündür.",
"Yaxınlarda vacib bir qərar verə bilərsən.",
"Gözlədiyin cavab yaxında gələ bilər.",
"Şansın yavaş-yavaş artır.",
"Yeni bir başlanğıc üçün doğru zamandasan.",
"Həyatında yeni bir fürsət doğa bilər.",
"Yaxınlarda səni xoşbəxt edəcək bir hadisə var.",
"Bir dostundan xoş bir xəbər ala bilərsən.",
"Gözlənilməz bir səyahət ola bilər.",
"Həyatında gözəl bir dəyişiklik yaxınlaşır.",
"Bu gün xoş bir hadisə yaşaya bilərsən.",
"Uzun zamandır istədiyin şey yaxında ola bilər.",
"Yeni bir ideya sənə uğur gətirə bilər.",
"Şanslı bir dövr başlayır.",
"Yaxınlarda həyatına yeni insanlar girə bilər.",
"Bir məsələdə daxili səsini dinləməlisən.",
"Gözlədiyin fürsət yaxında ortaya çıxa bilər.",
"Bu gün sənə ilham verəcək bir şey yaşaya bilərsən.",
"Bir hədəfin yaxında reallaşa bilər.",
"Həyatında gözəl bir sürpriz ola bilər.",
"Gözlənilməz bir inkişaf səni xoşbəxt edə bilər.",
"Yeni bir qapı açıla bilər.",
"Həyatında müsbət bir dönüş ola bilər.",
"Yaxınlarda səni sevindirəcək bir xəbər var.",
"Bir fürsəti yaxşı dəyərləndirməli ola bilərsən.",
"Bu gün şanslı bir qarşılaşma yaşaya bilərsən.",
"Həyatında yeni bir başlanğıc ola bilər.",
"Bir arzun reallaşmağa yaxındır.",
"Yaxınlarda vacib bir söhbət edə bilərsən.",
"Gözlənilməz bir dəstək ala bilərsən.",
"Yeni bir plan sənə uğur gətirə bilər.",
"Həyatında pozitiv bir dəyişiklik ola bilər.",
"Yaxınlarda sevindirici bir mesaj ala bilərsən.",
"Bu gün daxili hüzur hiss edə bilərsən.",
"Şansın getdikcə artır.",
"Bir qərar həyatını dəyişdirə bilər.",
"Yaxınlarda gözəl bir fürsət səni tapacaq.",
"Həyatında yeni bir yol açıla bilər.",
"Gözlənilməz bir xoşbəxtlik yaşaya bilərsən.",
"Bir dostun sənə dəstək ola bilər.",
"Bu gün enerjin olduqca yüksəkdir.",
"Həyatında ümidverici bir inkişaf ola bilər.",
"Yeni bir ideya uğur gətirə bilər.",
"Yaxınlarda səni xoşbəxt edəcək bir təklif ola bilər.",
"Həyatında gözəl bir sürpriz ola bilər.",
"Bu gün alacağın bir xəbər səni sevindirə bilər.",
"Yeni bir başlanğıc edə bilərsən.",
"Şanslı bir dövr başlayır.",
"Həyatında hüzur arta bilər.",
"Yaxınlarda bir arzun reallaşa bilər.",
"Gözlənilməz bir fürsət səni tapa bilər.",
"Bu gün vacib bir hadisə yaşaya bilərsən.",
"Yeni bir qapı açıla bilər.",
"Həyatında gözəl bir xəbər ola bilər.",
"Bir dostun sənə yaxşı bir ideya verə bilər.",
"Yaxınlarda sevindirici bir inkişaf olacaq.",
"Həyatında yeni bir başlanğıc ola bilər.",
"Bir hədəfin yaxında reallaşa bilər.",
"Gözlədiyin mesaj yaxında gələ bilər.",
"Yeni bir fürsət ortaya çıxa bilər.",
"Şansın artır.",
"Yaxınlarda səni xoşbəxt edəcək bir xəbər var.",
"Həyatında müsbət inkişaflar olacaq.",
"Bir qərar yeni qapılar aça bilər.",
"Yaxınlarda gözəl bir sürpriz yaşaya bilərsən.",
"Bu gün şans sənin yanında ola bilər.",
"Yeni bir başlanğıc səni gözləyir.",
"Həyatında ümid dolu bir dövr ola bilər.",
"Gözlənilməz bir təklif ala bilərsən.",
"Yaxınlarda gözəl bir tanışlıq ola bilər.",
"Şanslı bir gün yaşaya bilərsən.",
"Həyatında gözəl bir hadisə ola bilər.",
"Bir arzun yaxında reallaşa bilər.",
"Yeni bir fürsət qapını döyə bilər.",
"Bu gün gözəl bir xəbər ala bilərsən.",
"Həyatında yeni bir yol açıla bilər.",
"Gözlənilməz bir xoşbəxtlik yaşaya bilərsən.",
"Yaxınlarda sevindirici bir inkişaf ola bilər.",
"Şansın artmağa davam edir.",
"Həyatında gözəl bir dəyişiklik ola bilər.",
"Bir fürsət səni gözləyir.",
"Yeni bir qapı açıla bilər.",
"Bu gün şanslı bir gün ola bilər.",
"Yaxınlarda gözəl bir sürpriz ola bilər.",
"Həyatında yeni bir başlanğıc ola bilər.",
"Bir hədəfin yaxında reallaşa bilər.",
"Gözlənilməz bir fürsət səni tapa bilər.",
"Yeni bir plan sənə uğur gətirə bilər.",
"Yaxınlarda səni xoşbəxt edəcək bir hadisə var.",
"Həyatında gözəl bir dəyişiklik ola bilər.",
"Bir arzun reallaşa bilər.",
"Bu gün pozitiv bir inkişaf yaşaya bilərsən.",
"Yaxınlarda sevindirici bir xəbər ala bilərsən.",
"Həyatında yeni bir fürsət ola bilər.",
"Şanslı bir dövr başlayır.",
"Gözlənilməz bir dəstək ala bilərsən.",
"Yeni bir başlanğıc səni gözləyir.",
"Yaxınlarda gözəl bir sürpriz ola bilər.",
"Həyatında ümid dolu bir inkişaf ola bilər.",
"Bir qərar həyatında dəyişiklik gətirə bilər.",
"Yaxınlarda səni xoşbəxt edəcək bir xəbər var.",
"Bu gün gözəl bir fürsət yaxalaya bilərsən.",
"Həyatında yeni bir yol açıla bilər.",
"Şansın getdikcə artır.",
"Yaxınlarda gözəl bir hadisə ola bilər.",
"Gözlənilməz bir xoşbəxtlik yaşaya bilərsən.",
"Həyatında yeni bir başlanğıc ola bilər.",
"Bir arzun yaxında reallaşa bilər.",
"Yeni bir fürsət səni gözləyir.",
"Yaxınlarda sevindirici bir xəbər ala bilərsən.",
"Həyatında gözəl bir sürpriz ola bilər.",
"Bu gün şanslı bir inkişaf yaşaya bilərsən.",
"Yeni bir qapı açıla bilər.",
"Həyatında müsbət bir dəyişiklik ola bilər.",
"Yaxınlarda səni xoşbəxt edəcək bir inkişaf ola bilər.",
"Şanslı bir dövr səni gözləyir."
]
# ===== BÜRC ŞƏRHLƏRİ =====
burclar = {
    "qoç": "Enerjin yüksəkdir. Yeni başlanğıclar üçün uyğun bir gündür.",
    "buğa": "Maddi məsələlərdə diqqətli olmalı ola bilərsən.",
    "əkizlər": "Ünsiyyət və sosial ətraf ön plandadır.",
    "xərçəng": "Ailə və emosional mövzular gündəmdədir.",
    "şir": "Liderlik xüsusiyyətlərin diqqət çəkəcək.",
    "qız": "Detallara fokuslanaraq uğur qazana bilərsən.",
    "tərəzi": "Münasibətlərdə tarazlıq qurmağın vacibdir.",
    "əqrəb": "İntuisiyaların səni doğru yönləndirə bilər.",
    "oxatan": "Yeni ideyalar və planlar ortaya çıxa bilər.",
    "oğlak": "Çalışqanlığın sənə uğur gətirəcək.",
    "dolça": "Yaradıcı düşüncələrin ön plana çıxacaq.",
    "balıq": "Duyğuların və xəyal gücün güclüdür."
}

# ===== TAROT =====
tarot_kartlari = [
    "🃏 Dəli – Yeni başlanğıclar, macəra və bilinməyənə addım atmaq.",
    "🃏 Sehrbaz – Güc, bacarıq və potensialını istifadə etmək.",
    "🃏 Baş Kahinə – İntuisiyalar, gizli biliklər və daxili səsi dinləmək.",
    "🃏 İmperatriçə – Bərəkət, yaradıcılıq və şəfqət.",
    "🃏 İmperator – Avtoritet, nizam və liderlik.",
    "🃏 Əziz (Baş Kahin) – Ənənələr, bilik və ruhani rəhbərlik.",
    "🃏 Aşiqilər – Sevgi, harmoniya və vacib seçimlər.",
    "🃏 Savaş Arabası – Qətiyyət, irəliləyiş və qələbə.",
    "🃏 Güc – Daxili güc, səbr və cəsarət.",
    "🃏 Zahid – Daxili axtarış, tənhalıq və müdriklik.",
    "🃏 Tale Çarxı – Şans, tale və gözlənilməz dəyişikliklər.",
    "🃏 Ədalət – Tarazlıq, düzgünlük və ədalətli qərarlar.",
    "🃏 Asılmış Adam – Gözləmə, fədakarlıq və fərqli baxış bucağı.",
    "🃏 Ölüm – Böyük transformasiya və yeni başlanğıc.",
    "🃏 Tarazlıq – Səbr, harmoniya və orta yolu tapmaq.",
    "🃏 Şeytan – Asılılıqlar, ehtiraslar və gizli arzular.",
    "🃏 Qüllə – Ani dəyişiklik, sarsıdıcı hadisələr və köhnə nizamın yıxılması.",
    "🃏 Ulduz – Ümid, ilham və ruhani hüzur.",
    "🃏 Ay – Sirr, intuisiya və qeyri-müəyyənlik.",
    "🃏 Günəş – Xoşbəxtlik, uğur və pozitiv enerji.",
    "🃏 Məhkəmə – Oyanış, hesablaşma və vacib qərarlar.",
    "🃏 Dünya – Tamamlanma, uğur və yeni bir dövr."
]

# ===== YUXU =====
@app.on_message(filters.command("ruya"))
async def ruya(client, message: Message):

    if len(message.command) < 2:
        await message.reply("Yuxunu yaz.\nNümunə:\n`/ruya yuxuda ilan gördüm`")
        return

    text = " ".join(message.command[1:]).lower()
    bulunan = []

    for kelime, yorum in ruya_sozluk.items():
        if kelime in text:
            bulunan.append(f"🔎 **{kelime}** → {yorum}")

    if bulunan:
        await message.reply("🌙 **Yuxu Analizi**\n\n" + "\n".join(bulunan))
    else:
        await message.reply("🔮 Yuxuda aydın bir simvol müəyyən edilmədi.")

# ===== FAL =====
@app.on_message(filters.command("fal"))
async def fal(client, message: Message):

    cevap = random.choice(fal_listesi)

    await message.reply(f"🔮 **Fal Şərhi**\n\n{cevap}")

# ===== BÜRC =====
@app.on_message(filters.command("burc"))
async def burc(client, message: Message):

    if len(message.command) < 2:
        await message.reply("Bürcünü yaz.\nNümunə:\n`/burc şir`")
        return

    burc_adı = message.command[1].lower()

    if burc_adı in burclar:
        await message.reply(f"♈ **{burc_adı.capitalize()} Bürcü**\n\n{burclar[burc_adı]}")
    else:
        await message.reply("Düzgün bir bürc adı yaz.")

# ===== SEVGİ UYUMU =====
@app.on_message(filters.command("askuyumu"))
async def ask(client, message: Message):

    if len(message.command) < 3:
        await message.reply("Nümunə:\n`/askuyumu qoç əqrəb`")
        return

    oran = random.randint(40, 100)

    await message.reply(f"❤️ **Bürc Uyğunluğu**\n\nUyğunluq faizi: **%{oran}**")

# ===== TAROT =====
@app.on_message(filters.command("tarot"))
async def tarot(client, message: Message):

    kart = random.choice(tarot_kartlari)

    await message.reply(f"🃏 **Tarot Kartın**\n\n{kart}")
