import random
from pyrogram import filters
from pyrogram.types import Message
from AloneMusic import app

# Doğruluk soruları
dogruluk_listesi = [
    "Heç kimə demədiyin bir sirrini paylaşarsan?",
    "Hazırda ən çox utandığın anını danışarsan?",
    "Heç kimə demərəm dediyin, amma burada açıqlaya biləcəyin bir şey var?",
    "Heç birinə yalan danışıb sonradan peşman olmusan?",
    "Həyatda ən çox kimə güvənirsən?",
    "İndiyə qədər etdiyin ən böyük axmaqlıq nə idi?",
    "Heç kimdənsə gizlicə xoşun gəlib? Kim idi?",
    "Ailəndən gizlətdiyin ən böyük sirr nədir?",
    "Dostlarına heç xəyanət etmisən?",
    "Bir günlüyünə görünməz olsan ilk nə edərdin?",
    "Uşaqkən etdiyin ən böyük dəcəllik nə idi?",
    "İlk sevginiz hələ də xatırlayırsan?",
    "Heç sosial mediada stalk etmisən?",
    "Sevdiyin birinə yalan danışmısan?",
    "Məktəbdə başına gələn ən gülməli hadisə nə idi?",
    "Hazırda ən böyük xəyalın nədir?",
    "Heç dava etmisən? Səbəbi nə idi?",
    "Xoşun gələn şəxsə hisslərini deyib rədd cavabı almısan?",
    "Səndən gizlədilən bir şeyi öyrənmək istəsən, bu nə olardı?",
    "Bir daha əsla etmərəm dediyin bir şey var?",
    # Ek 50 soru
    "Heç böyük bir sirri üzə çıxarmaq məcburiyyətində qalmısan?",
    "Ən utanc verici anını danışarsan?",
    "Heç aşiq olduğun insanı itirmisən?",
    "Həyatda ən çox peşman olduğun şey nədir?",
    "Heç oğurluq etdiyin bir şey olub?",
    "Ən böyük qorxun nədir?",
    "Bir dostuna zərər vermisən?",
    "Heç gizlicə birinə baxarkən yaxalanmısan?",
    "Həyatındakı ən böyük başarın nədir?",
    "Heç birinə səhvən böyük bir yalan danışmısan?",
    "Ən mənasız yuxunda nə görmüsən?",
    "Özünlə bağlı utanc verici bir vərdişin var?",
    "Heç birinə aşiq olub demədiyin olub?",
    "Həyatında kimsənin bilmədiyi bir hobbin var?",
    "Heç birini qısqanmısan?",
    "Hazırda sənə ən çox kədər verən şey nədir?",
    "Heç kiminsə haqqında qeybət etmisən?",
    "Həyatında verdiyin ən peşman qərar nədir?",
    "Heç birini gizlicə təqib etmisən?",
    "Ən utanc verici mesajını paylaşa bilərsən?",
    "Heç özünü səhv ifadə etmisən?",
    "Ən sevdiyin uşaqlıq oyuncağın nə idi?",
    "Birinə qarşı yalan danışmaq məcburiyyətində qalmısan?",
    "Heç birinə gizlicə kömək etmisən?",
    "Heç aşiq olduğun şəxs tərəfindən rədd edilmisən?",
    "Ən xoşlamadığın vərdişin nədir?",
    "Birinə xəyanət etmisən?",
    "Heç birinə böyük bir sirr vermisən?",
    "Həyatında ən çox qürur duyduğun an hansıdır?",
    "Heç birinə qırıcı bir şey demisən?",
    "Heç kimə demədiyin bir xəyalını paylaşarsan?",
    "Ən yaxın dostunu qısqanmısan?",
    "Heç kimlə dava etmisən?",
    "Birinə xəyanət etdiyini fərq etmisən?",
    "Heç gizli bir istedadın var?",
    "Ən böyük uğursuzluğun nədir?",
    "Birinə özünü ifadə edə bilmədiyin an olub?",
    "Heç birini səhv anlamısan?",
    "Həyatında ən çox qorxduğun an nə idi?",
    "Heç kimə etiraf edə bilmədiyin bir duyğun var?",
    "Ən böyük yalanın nə idi?",
    "Heç kim haqqında səhv fikirdə olmusan?",
    "Ən böyük sirrini kimlə paylaşa bilərsən?",
    "Heç kim üçünsə ağlamısan?",
    "Heç aşiq olub qarşılıq görmədiyin olub?",
    "Heç kim haqqında gizlicə düşündüyün bir şey var?",
    "Həyatında aldığın ən çətin qərar nə idi?",
    "Ən sevdiyin uşaqlıq xatirən nədir?",
    "Heç kim üçünsə fədakarlıq etmisən?",
    "Ən utanc verici vərdişin nədir?",
    "Heç kim üçünsə peşmanlıq duymusan?",
    "Həyatında unuda bilmədiyin biri var?",
]

# Cesaret soruları
cesaret_listesi = [
    "Elə indi ən yaxın dostuna 'Səni sevirəm' yaz və ekran şəklini paylaş!",
    "Qrup daxilində təsadüfi birinə gülməli bir ləqəb qoy!",
    "Özün haqqında utanc verici bir həqiqəti səsli mesajla de!",
    "Telefonundakı son mesajı burada paylaş!",
    "Birinə zəng edib ona mahnı oxu!",
    "Qrupa ən gülməli selfini at!",
    "Hazırda yanında olan bir əşyanın şəklini çəkib göndər!",
    "Bir dostunun profil şəklini təqlid et və paylaş!",
    "Qrup içindən təsadüfi birini təriflə!",
    "Ən sevmədiyin yeməyi etiraf et və səbəbini izah et!",
    "İndi ən yaxın dostuna mənasız emojilər göndər!",
    "Son zəng tarixçəsini burada paylaş!",
    "Heç danışmadığın birinə salam de!",
    "Qrup içindən birinin adını tərsinə de!",
    "İndi gözlərini bağlayıb təsadüfi bir stiker göndər!",
    "Yanındakı insandan səni təsvir edən üç söz deməsini istə!",
    "1 dəqiqə ərzində yalnız emojilərlə danış!",
    "Öz telefonunda ilk gördüyün şəkli paylaş!",
    "Qrup içindən birinə təsadüfi kompliment de!",
    "Hazırda ağlına gələn ilk mahnının nəqarətini yaz!",
    # Ek 50 soru
    "Elə indi qrupun ən səssiz üzvünə zarafat et!",
    "Yanındakı insana ən gülməli mahnını oxu!",
    "Qrupun ən yaşlı üzvünə emoji ilə mesaj at!",
    "Telefonunda ən son çəkdiyin şəkli paylaş!",
    "Yanındakı şəxsə ən gülməli komplimenti et!",
    "Birinə 1 dəqiqə ərzində yalnız emoji ilə cavab ver!",
    "Telefonundakı ən köhnə şəkli paylaş!",
    "Qrup içindən təsadüfi birinə zarafat et!",
    "Elə indi gülməli bir rəqs et və videoya çəkib göndər!",
    "Qrup daxilində birinə şişirdilmiş təriflər de!",
    "Ən qəribə səsinlə təqlid et və göndər!",
    "Qrup söhbətində təsadüfi bir mahnı sözü yaz!",
    "Telefonundakı son videonu paylaş!",
    "Yanındakı insana ən mənasız sualı ver!",
    "Tez bir dostuna qəribə bir zarafat et!",
    "Birinə gülməli bir ləqəb qoş!",
    "Telefonunda ən qəribə tətbiqi paylaş!",
    "Qrup daxilində təsadüfi birinə kompliment de!",
    "Yanındakı şəxsə təsadüfi emoji göndər!",
    "Kimisə təqlid et və paylaş!",
    "Qrupda təsadüfi birini etiketlə və gülməli bir şey yaz!",
    "Tez özünü təsvir edən üç söz de!",
    "Qrupda 1 dəqiqə ərzində yalnız GIF göndər!",
    "Yanındakı insana mahnı oxu!",
    "Telefonunda ən son dinlədiyin mahnını paylaş!",
    "Qrup söhbətində təsadüfi birinə mesaj at!",
    "Öz səsini dəyişdirib mesaj at!",
    "Qrup içindən birinə şişirdilmiş kompliment et!",
    "Telefonunda ən son göndərdiyin stikeri paylaş!",
    "Yanındakı şəxsə ən gülməli ləqəbi qoş!",
    "1 dəqiqə ərzində yalnız gülməli səslər çıxar!",
    "Qrupda təsadüfi birinə gülməli emoji göndər!",
    "Bir dostuna gizli bir mesaj yaz!",
    "Telefonundakı ən son zəngi paylaş!",
    "Tez özünə ən gülməli adı qoy!",
    "Qrup içindən təsadüfi birinə zarafat et!",
    "Yanındakı insana təsadüfi bir hekayə danış!",
    "Telefonunda ən mənasız şəkli paylaş!",
    "Qrup söhbətində təsadüfi birinə tərif yaz!",
    "1 dəqiqə ərzində yalnız mahnı sözləri yaz!",
    "Bir dostuna ən mənasız emojini göndər!",
    "Yanındakı şəxsə gülməli bir ləqəb qoş!",
    "Qrupda təsadüfi birinə zarafat göndər!",
    "Telefonundakı son video yazısını paylaş!",
    "Tez bir dostuna gülməli bir səs göndər!",
    "Qrup daxilində təsadüfi birinə gülməli ləqəb ver!",
    "Yanındakı şəxsə təsadüfi bir emoji göndər!",
    "1 dəqiqə ərzində yalnız gülməli mesajlar yaz!",
    "Telefonundakı ən son selfini paylaş!",
    "Qrup içindən təsadüfi birinə zarafat et!",
]

@app.on_message(filters.command(["d", "c"]))
async def dogruluk_cesaret(c: app, m: Message):
    command = m.command[0]

    if command == "d":
        return await m.reply_text(
            f"**✅ Doğruluq yoxsa? ❓ Cəsarət?**\n\n"
            f"{m.from_user.mention} Doğruluq sualını seçdi!\n\n"
            f"{random.choice(dogruluk_listesi)}"
        )

    elif command == "c":
        return await m.reply_text(
            f"**✅ Doğruluq yoxsa? ❓ Cəsarət?**\n\n"
            f"{m.from_user.mention} Cəsarət tapşırığını seçdi!\n\n"
            f"{random.choice(cesaret_listesi)}"
        )
