import random

mani = (
    """**Çadıra sərmişəm keçə,
Qoyunu sürdüm gecə.
O günlər də gələrmi?
Əlin əlimə keçə.**""",
    """**İşlədim arı kimi,
Pətəyin balı kimi.
Qız sən məni əritdin,
Dağların qarı kimi.**""",
    """**Badımcanı haşladım,
Doldurmağa başladım.
Dedilər yarın gəlib,
Oynamağa başladım.**""",
    """**Su gəlir axmaq ilə,
Dərəni yıxmaq ilə.
Sevən yara doyar mı?
Uzaqdan baxmaq ilə.**""",
    """**Portağal dilim-dilim,
Gəl otur mənim gülüm.
Mən sənə nə dedim ki,
Tutulsun mənim dilim.**""",
    """**Mani manini açar,
Mani könlümü açar.
İkisini sən söylə, birini mən,
Hansımız üstə çıxar.**""",
    """**Baxçalarda babatca,
Açılır ağca-ağca.
Qaçdım qarşıma çıxdı,
Tombul yanaqlı Xatca.**""",
    """**Çiyələkdən etdim mürəbbə,
Qara gün gələr keçər.
Dərdimi söyləyə bilmərəm,
Qəlbimdən nələr keçər.**""",
    """**Ləçəyin bucağında,
Od olar ocağında.
Allah canımı alsın,
O yarın qucağında.**""",
    """**Bağa girdim xurmaya,
Ovçu gəldi vurmaya.**""",
    """**Yada bağışlanar mı,
Baxçada turş alma.**""",
    """**Dolu vurdu bağıma,
Yel atdı yarpağını.
Qorxuram qərib öləm,
Yad atar torpağımı.**""",
    """**Pəncərəsi Orxundan,
Bir yar sevdim Zorkundan.
Kaş sevməz olaydım,
Ödü qopdu qorxudan.**""",
    """**Baxçalarda mum dirək,
Suyu hardan endirək.
Rəzil gəlin gedir,
Uyuz itə mindirək.**""",
    """**Sıra-sıra qazanlar,
Qara yazı yazanlar.
Cənnət üzü görməsin,
Aramızı pozanlar.**""",
    """**Bağa girdim xurmaya,
Ovçu gəldi vurmaya.**""",
    """**Büküb cibimə qoydum,
Nə gözəlsən Maşallah.
Kənar qızlarını,
Şeytan çarpar inşallah.**""",
    """**Faytonun pəncərəsi,
Əlindədir cərəsi.
Kiçik ikən gəlin olub,
Nədir bunun tələsi.**""",
    """**Qaladan endim durdum,
Bir cüt göyərçin vurdum.
Qız dəsmalın nə gözəl.**""",
    """**Poçtada pulçusan,
Meşələrdə qolçusan.
Meyl versəm söz versəm,
Əl qulaqda yolçusan.**""",
    """**Höpək-höpək tikanlar,
Aba köynək biçənlər.
Baxışından bəllidir,
Qara sevda çəkənlər.**""",
    """**Qaşların qarasına,
Mim çəkmiş arasına.
Sənə cərrah deyirlər,
Ürəklər yarasına.**""",
    """**Həbsxananın qapısı,
Dəmirdəndir yapısı.
Yarımın günü varmış,
Bir ay daha həbsi.**""",
    """**Örtüyü əyirmisən,
Qaşına dəyirmisən.
Çox da gözəl deyildin,
Özünü sevdirmisən.**""",
    """**Qız əntarin eflatun,
Dön də arxana baxın.
Sənin kimi gözəli,
Vermərəm eldən saxın.**""",
    """**Bir budaqda iki vişnə,
Gözəlim eşqə düşmə.
Bu eşqin sonu yoxdur,
Boş yerə dilə düşmə.**""",
    """**Baxçada turş alma,
Nə gözəlsən Maşallah.
Qonşu qızlarını,
Şeytan çarpar inşallah.**""",
    """**Mantuvarım mantuvar,
Mantuvarın vaxtı var.
Mantuvara gələnin,
Cənnətdə bir taxtı var.**""",
    """**Nazlıya bax nazlıya,
Evin uca deyilmi?
Düzünü deyin qonşular,
Nazlı tayım deyilmi?**""",
    """**Oğlanın adı Yılmaz,
Olmaz aslanım olmaz.
İçindən gəl-gel deməsə,
O evdə keçim olmaz.**""",
    """**Ay doğar sini kimi,
Sininin yanı kimi.
O yar məni sevir,
Bədəndə canı kimi.**""",
    """**Nərdivanı qırxayaq,
Qırxına vurdum dayaq.
Yar gəlir dedilər,
Qaçdım mən yalınayaq.**""",
    """**Şu təpənin alıcısı,
Qırmızıdır başlığı.
Şaftalı verməyənin,
Qəbul olmaz orucu.**""",
    """**Yaşıl sandıq kilidi,
Üstünü gül bürüdü.
Qız sən orda mən burda,
İman taxtam çürüdü.**""",
    """**Kəkliyim seker ağlar,
Tükünü tökər ağlar.
Anasız gəlin olan,
İçini çəkər ağlar.**""",
    """**Sırma hörüklü yarım,
Bəyaz biləkli yarım.
Necə mənsiz durursan,
Mərmər ürəkli yarım.**""",
    """**Suna mənəmi gəldin,
Ayaq basamı gəldin.
Sağlığımda gəlmədin,
Öldüm yasamı gəldin.**""",
    """**Kiçik ovalı gəldi,
Atlı dəvəli gəldi.
Başıma bu sevdalar,
Səni sevəli gəldi.**""",
    """**Qaşların emi-emi,
Nə baxan kinlə mənə.
Yat dizimin üstünə,
Çəkim sənə laylay.**""",
    """**Yana bilmərəm bilə-bilə,
Mən düşdüm qürbət ilə.
Yeddi dəsmal çürütdüm,
Gözüm yaşın silə-silə.**""",
    """**Siyah zülüflü canım,
Neştər vur axsın qanım.
Nar göbək fincan olsun,
Doldur içim canım.**""",
    """**Ağaclarda mazılar,
Könül səni arzular.
Yar ağlıma gələndə,
Ürəyim sızıldar.**""",
    """**Qarşıda duran sənsən,
Zülfünü buran sənsən.
Mənə cəllad kar etməz,
Boynumu vuran sənsən.**""",
    """**Bu gün hava qaraldı,
Bətim-bənizim saraldı.
Baş əcəl yastığında,
Qolum yarı saraldı.**""",
    """**Qar yağar kiriş kimi,
Əridim gümüş kimi.
Mən yarı arzuladım,
Tufanda yemiş kimi.**""",
    """**Yel vurar qazaq oynar,
Başımda tozaq oynar.
Mən yarıma nə etdim,
O məndən uzaq oynar.**""",
    """**Tarla başı pıtıraq,
Duraq qatar-qatar.
Çox çalışdıq yetməzmi?
Gəlin qızlar oturaq.**""",
    """**Dəsmalları qoxulu,
Yan cibində soxulu.
Nə vaxt bağlanacaq,
Dağıstanın məktəbi.**""",
    """**Gəl yaxına-yaxına,
Çeşmənin arxasına.
Qırmızı gül taxım,
Ceketin yaxasına.**""",
    """**Qayalardan sürüşərəm,
Bu qız mənim tayımdır.
Ayşə mənim olmazsa,
Taleyimə yanaram.**""",
    """**Yel vurar qazaq oynar,
Başımda tozaq oynar.
Mən yarıma nə etdim,
O məndən uzaq oynar.**""",
    """**Tarla başı pıtıraq,
Duraq qatar-qatar.
Çox çalışdıq yetməzmi?
Gəlin qızlar oturaq.**""",
    """**Dəsmalları qoxulu,
Yan cibində soxulu.
Nə vaxt bağlanacaq,
Dağıstanın məktəbi.**""",
    """**Gəl yaxına-yaxına,
Çeşmənin arxasına.
Qırmızı gül taxım,
Ceketin yaxasına.**""",
    """**Qayalardan sürüşərəm,
Bu qız mənim tayımdır.
Ayşə mənim olmazsa,
Taleyimə yanaram.**""",
    """**Baxça-baxça gəzərəm,
İnci muncuq düzərəm.
Baxın indi üzümə,
Bu kənddə ən gözələm.**""",
    """**Qara daşın kənarı,
Üstündə qırdım narı.
Tutulası dillərim,
Necə incitdin yarı.**""",
    """**Yuvasında qaranquş,
Qanadı ayrı-ayrı.
Dönə qızı sevənlər,
Qan qussun ovuc-ovuc.**""",
    """**Əlində var yelpik,
Quş dadanıb gilasa.
Yaxında gələcəyəm,
Özünü çəkmə naza.**""",
    """**Məni məni neyləyim,
Hansı gündə gəlim.
Yadın yarı gözəldir,
Mən çirkini neyləyim.**""",
    """**Masa üstündə bıçaq,
Sanki mənə vuracaq.
Ana xəbərin olsun,
Qardaşım qız qaçıracaq.**""",
    """**Gül kimi oyum-oyum,
Qısacıq qaldı boyum.
Alacaqsansa al indi,
Bəsdir etdiyin oyun.**""",
    """**Çaya vardım çayladım,
Çayda balıq ovladım.
Balıq deyil məqsədim,
Mən könlümü əylədim.**""",
    """**Qatar yolunda tütün,
Yarpağı bütün-bütün.
Həm ata həm anadan,
Qoyma Allahım yetim.**""",
    """**Gedə-gedə yoruldum,
Bir kənara oturdum.
Gözəlliyinə deyil,
Ədanına vuruldum.**""",
    """**Məscidin minarəsi,
Məktəbin pəncərəsi.
Şu kənarın qızları,
Bulaşıq tencərəsi.**""",
    """**Albalı budaqlı,
Məryəm albalı dodaqlı.
Yarım dünya gözəli,
Alma kimi yanaqlı.**""",
    """**Dərələrə gedək,
Qoyun-quzu güdək.
İkimizi görüblər,
Necə inkar edək.**""",
    """**Qəbiristanlığın daşını,
Qoyunmu sandın yarım.
Sevib də ayrılmağı,
Oyunmu sandın yarım.**""",
    """**Al geyindim alsın deyə,
Bənövşəyi geyindim sarsın deyə.
İsteyənə getmədim,
Sevdiyim alsın deyə.**""",
    """**Qarşıdan yar gəlir,
Donu dar gəlir.
Mən sevdim özgələr aldı,
O mənə ar gəlir.**""",
    """**Göy üzündə təyyarə,
Önündədir pərvanə.
Qaş-göz oynatsam oğlan,
Olacak bir divanə.**""",
    """**Dükanlarda toz şəkər,
Şəkərlər kilo çəkir.
Səni kafirin oğlu,
Gördüyünə ah çəkir.**""",
    """**Qızın adı gül Fatma,
Ayranlara su qatma.
Utanıram canım,
Yolda mənə söz atma.**""",
    """**Gedə-gedə yoruldum,
Bir daldada oturdum.
Pəzəvəngin oğluna,
Bir baxışda vuruldum.**""",
    """**Anam əntari alıb,
Ağ xətti varmış.
Bir yar sevdim bilmədən,
Onun da yarı varmış.**""",
    """**Qaralar qarda qaldı,
Bülbüllər zarda qaldı.
Könül qapısı bağlı,
Açar yarda qaldı.**""",
    """**Qara kütük yanır,
İçində çay qaynayır.
Heç baxın qonşular,
Nə də gözəl oynayır.**""",
    """**Qəhvə bişdiyi yerdə,
Bişib daşdığı yerdə.
Gözəl-çirkin aranmaz,
Könül düşdüyü yerdə.**""",
    """**Osmaniye üst tərəf,
Oturma qışda daşda.
Mən sənlə əylənirəm,
Mənim sevdiyim başqa.**""",
    """**Dəsmalım yellənir,
Şu könlüm əylənir.
Şu kənarın qızları,
Oğlanmı bəyənir.**""",
    """**Qonağın pəncərəsi,
Nə zalımdır gecəsi.
Sənə kim aşiq olar,
Küçələr əyləncəsi.**""",
    """**Çeşmənin daşı kimi,
Gözünün yaşı kimi.
Elə bir qız sevdim ki,
Kanarya quşu kimi.**""",
    """**Qayalarda sürüşərəm,
Yoxdur mənim ayarım.
Mən sevdadan ölsəm,
Taleyimə yanaram.**""",
    """**Maşınlar gəlir,
Bacım gəlin olur.
O ərə gedəndə,
Növbə mənə gəlir.**""",
    """**Çay qırağında kolluq,
Boğazında altılıq.
Yaxşı baxın oğlanlar,**""",
    """**Oynayanlar satlıq**""",
    """**Qaşları ox sevdiyim,
Canımdan çox sevdiyim.
Həmişə gözəllər gəlir,
İçində yox sevdiyim.**""",
    """**Yumurtası yuvada,
Oturur yollarda.
Hamı toy edir,
Bizim toy bolluqda.**""",
    """**Dam üstündə yuvarlaq,
Dərə axır şır-şır.
Mənim sevdiyim yarım,
Doğan aydan parlaq.**""",
    """**Sıra-sıra bazarlar,
Yarım məni qarşılar.
Gizli-gizli danışdım,
İndi duydu qonşular.**""",
    """**Bir daş atdım qarğaya,
Dönüb baxdım arxaya.
Əvvəl candan sevərdim,
İndi vurdum dalğaya.**""",
    """**Almanı yükə qoydum,
Ağzını dikə qoydum.
Aldım yarın əlindən,
Boynunu bükə qoydum.**""",
    """**Qərənfil haşlanar mı?
Dibçəyi daşlanar mı?
Uşaq ikən yar sevdim,
Yada bağışlanar mı?**""",
    """**Pəncərədə duran qız,
Bayram gəldi dolan qız.
Qurbansız bayram olmaz,
Sənə olum qurban qız.**""",
    """**Qarşıdan baxma yarım,
Qaşlarını çatma yarım.
Mən köhnə zarafatcılam,
Heç əda satma yarım.**""",
    """**Qar yağar saçaqlara,
Tökülər küçələrə.
Necə ana doğub,
Sığmır qucaqlara.**""",
    """**Üzüyüm daşa gəldi,
Bir qələm başa gəldi.
Sevda nədir bilməzdim,
Nə çarə başa gəldi.**""",
    """**Həbsxananın qapısı,
Dəmirdəndir yapısı.
Yarımın günü varmış,
Bir ay daha həbsi.**""",
    """**Örtüyü əyirmisən,
Qaşına dəyirmisən.
Çox da gözəl deyildin,
Özünü sevdirmisən.**""",
    """**Qız əntarin eflatun,
Dön də arxana baxın.
Sənin kimi gözəli,
Vermərəm eldən saxın.**""",
    """**Bir budaqda iki vişnə,
Gözəlim eşqə düşmə.
Bu eşqin sonu yoxdur,
Boş yerə dilə düşmə.**""",
    """**Mantuvarım mantuvar,
Mantuvarın vaxtı var.
Mantuvara gələnin,
Cənnətdə bir taxtı var.**""",
    """**Nazlıya bax nazlıya,
Evlərin uca deyilmi?
Düzünü deyin qonşular,
Nazlı tayım deyilmi?**""",
    """**Oğlanın adı Yılmaz,
Olmaz aslanım olmaz.
İçindən gəl-gel deməsə,
O evdə keçim olmaz.**""",
    """**Ay doğar sini kimi,
Sininin yanı kimi.
O yar məni sevir,
Bədəndə canı kimi.**""",
    """**Dağda fıstıq olar mı?
Atəş yastıq olar mı?
Sən orda mən burda,
Belə dostluq olar mı?**""",
    """**En dərəyə dərəyə,
Dərə çınqıllı yarım.
Hər keçənə baxır,
Yarım ağıllı yarım.**""",
    """**Baxçalarda portağal,
Getmə yarım burda qal.
Sən şəhərə ensən,
Mənə şüşə bardaq al.**"""
)

espri = [
    "Sonuncu gülən ən gec anlayandır.",
    "İnsanların səni əzməsinə icazə vermə. Sürücülük vəsiqəsi al, sən onları əz...",
    "İlahi Əzrayıl... Sən adamı öldürürsən!",
    "Mən mafiya atasıyam, çünki oğlumun adı Mafiyadır.",
    "Kimvurduya getdim, bir azdan gələcəyəm.",
    "Varlı xəngəl yeyir, kasıb isə qəm-qüssə.",
    "Hava qulduru təyyarəni qaçıracaqdı, amma alınmadı, çünki təyyarəyə gecikdi.",
    "Get 'arı' gətir bir az mahnı oxuyaq.\n   -Əmi, arı sancmasın!",
    "Ürəyin sıxılırsa, kəmərini boşalt.",
    "Bakıda bakılılar, Sumqayıtda sumqayıtlılar yaşayar.",
    "Sənə bir qılllıq edim, qıllarını qoyarsan.",
    "Seven unutmaz oğlum, eight unudar.",
    "Yat, üstünü örtüm üşüməyəsən.",
    "Gəl dəyirmana gedək bir-iki tələ quraq, bəlkə dən tutduq.",
    "Adamın biri günəşdə yanıb, ay isə düz.",
    "Kinoda 10 dəqiqə ara dedi, aradım-aradım açmadı.",
    "Rentgen filmi çəkdirdik, yaxında kinoteatrlarda.",
    "Dünən taksi çevirdim, hələ də fırlanır.",
    "Mən hekayə yazaram, Əbru Dastan.",
    "Dünən keçmiş günlərimi aradım, amma məşğul idi.",
    "Təbriklər qazandınız, indi qazan oldunuz!",
    "Qaba qüvvə tətbiq etmə, qab qırıla bilər.",
    "Güzgünün qarşısında bəzənmə, Manqanın qarşısında bəzən.",
    "Dünən tor çulki aldım, zürafəyə almadım.",
    "İlanlardan qorxma, ilanların içində olandan qorx.",
    "Mən qəhvə içirəm, Nurgül Yeşilçay.",
    "Bax o qarşıdakı təyyarə PİSTİ, amma bir cür təmizləmədilər.",
    "Dünən keçmiş günlərimi aradım, amma məşğul idi.",
    "Adamın biri televizora çıxıb, bir də düşürə bilməyiblər.",
    "Adamın biri gülüb, dibçəyə qoyublar.",
    "Funda Arar dedilər, amma hələ də axtarmayıb.",
    "Adamın başı atıb, ayaqları eşşək.",
    "Uzun sözün qısası: U.S.Q.",
    "Yağış yağmış, qar pendir!",
    "Saxla samanı, inəklər ac qalsın.",
    "Bənd dendi mi, axan sular durur.",
    "Dünya fırlanarmış, ay da köftə...",
    "Sonuncu gülən ən gec anlayandır.",
    "Bu erikson, başqa erik yoxdur.",
    "Sən yük maşınını götür, Leonardo da vinci.",
    "Adamın biri gülüb, baxçaya əkiblər.",
    "Top qapıdadır, mən ağlamaz mıyım?",
    "Mən gəzək deyirəm, Gerard Depardieu.",
    "Əhməd saz çaldı, polis tutdu.",
    "Məni ayda bir dəfə kinoya aparma, Marsda bir dəfə apar.",
    "Mən çörək yedim, Will Smith.",
    "Aaaaa siz çox tərləmisiniz, durun sizə tər-lik gətirim.",
    "Qəlbinin səsini dinlə, gözəldirsə kaset çıxart.",
    "Bağırsaqlarda yaşayan qurdlar bağırsaqda yaşarlar, bağırmasaq da yaşarlar.",
    "Çiçəyin biri solub, digəri isə sağ.",
    "Xahiş edirəm sakit olun, telefon faturasını yeni yatırtdım, yatır indi, oyanmasın.",
    "Nuri ölincə Çində basdırsınlar, nur içində yatsın.",
    "Temel qəhvədə işə başlayır, müştərilərdən biri səslənir:\n   -Temel bizə üç çay, biri açıq olsun.\n   -Hansı?",
    "Temel bir gün Fransaya gedib:\n   -Aaa buranı da mı Sabancı alıb, deyib.",
    "İngilis dilim yoxdur, tanıdığım bütün Cəmlər türkdür.",
    "Sarımsağı havanda döymüsən, ha Şuşada.",
    "Dondurmanı mən yalamam, himalayalar.",
    "Yarasa xeyirli heyvandır. Xeyirli olmasaydı 'yaramasa' deyərdi.",
    "Kəpənəklər, köstəbəklər, amma mən gözləmərəm.",
    "Bütün ümidlərim suya düşdü, amma boğulmadılar. Çünki onlara üzməyi öyrətmişdim.",
    "Bu gecə səni qınayıram, çünki xına gecəsidir.",
    "Pilləkəndə durmayın, avtomatik qapı vurar, bölər, kvadrat kökün alar.",
    "Maşın almısan, xeyirli olsun. Bəli, aldıq. Niyə maşın aldın ki, özünə alsaydın.",
    "Çox Məqbule keçdi, indi də Fatma keçir.",
    "Əlinin salamı var.\n   Hansı Əlinin?\n   Şəhərlərarası avtobus termin-ali",
    "-Abi sənə Sılanın salamı var.\n   -Hansı Sılanın?\n   -Ümumi Daxili HaSıla",
    "Sən o dəstəni tanıyırsan?\n   -Hansı dəstəni?\n   -Pe-dəstəni (Peçeteni).",
    "Eynəyin nömrəlidir?\n   -Yox, qapı arxası",
    "Erkək ata nə deyilir?\n   Bayat",
    "Ən gözəl çay hansı dağda içilir?\n   Çay bardağında",
    "4-cü Murad niyə intihar edib?\n   – İlk 3-lüyə girə bilmədiyi üçün",
    "Dünən dostlarla sobada kartof yeyirdik, soba isti gəldi baxçaya çıxdıq.",
    "Masada hansı örtük istifadə olunmaz?\n   – Bitki örtüyü.",
    "Adamın başı atıb, ayaqları eşşək.",
    "Dünən keçmiş günlərimi aradım, amma məşğul idi.",
    "Sinus 60, kosinus tutub...",
    "Yağış yağmış, qar pendir!",
    "Bənd dendi mi, axan sular durur.",
    "Pişiklər niyə hava limanına gedə bilmir? Çünki pist var (pissdir)."
]

slapmessage = [
    "{}, {}**'a Fosfor Bombası Atdı! Qanunlara Ziddir??!**",
    "{}, {}**'in Üzünə Pomidor Tulladı! Üzü qıpqırmızı oldu ??**", 
    "{}, {}**'in Saçını Çəkdi!**", 
    "{}, {}**'nin Üzünə Yumruq atdı! Buz qoy göyərməsin ??**", 
    "{}, {}**'ə Kəllə Atdı! Burnu qırıldı deyəsən ??**", 
    "{}, {}**'ə Uçan Təpik Atdı! Jetlisən mübarək ??**", 
    "{}, {}**'ə Divanı Tulladı! Elə ölməz, raket atsaydın ??**", 
    "{}, {}**'ə İynə batırdı! Bu incitmiş olar deyəsən ??**", 
    "{}, {}**'a Yumurta Tulladı! Tam isabət ??**", 
    "{}, {}**'ə Çiyin atdı! Nə baxırsan birader?**", 
    "{}, {}**'ə Ayaq atıb yıxdı!**", 
    "{}, {}**'ə Su Qabı Tulladı! Ümid edirəm qaba bir şey olmayıb ??**", 
    "{}, {}**'in Üstünə Çay Tökdü! Yanırsan Fuad əmi ??**", 
    "{}, {}**'in Başında Şüşə Qırdı! Acımış olar ??**",
    "{}, {}**'in Üzünə Tüpürdü! Bax bunu etməməli idin ??**", 
    "{}, {}**'ə Daş Atdı! Aha, başı yarıldı ??**", 
    "{}, {}**'ə Osmanlı Silləsi Atdı! Sillə-qapaz etdi yazıq uşağı ??**", 
    "{}, {}**'ə Banka Tulladı! Başqa bir şey tapmadı deyəsən ??**",
    "{}, {}**'in Ayağının Altına Banan Tulladı! Ayağı Sürüşdü ??**",
    "{}, {}**'ə Zibil Qabı Tulladı! Üstü-başı Zibil Oldu ??**",
    "{}, {}**'in Üstünə Yük Maşını Sürdü! Altında Qalmaqdan Son Anda Qurtuldu ??**",
    "{}, {}**'in Gözünə Barmağını Soxdu! Bu Həqiqətən Acıtmış Olar ??**", 
    "{}, {}**'ə Yolda Gedərkən Ənsəsinə Sillə Atdı! Və Qaçmağa Başladı??**",
    "{}, {}**'in Üzünə Turşu Atdı! Ah Be Bergenim??**",   
    "{}, {}**'i Qiymə Maşınına Atdı! Omega5 dadındadır??**",  
    "{}, {}**'ə F35 Tulladı!! Müharibə Başlasın??**",   
    "{}, {}**'ə Tort Atdı!! Çimmək Şərt Oldu.??**",
    "{}, {}**'ə Başmaq Tulladı!! Tam İsabət, Ana Namizədisən bəyəm????**",  
    "{}, {}**'in Üstünə Benzin Töktü Və Od Vurdu!??**",
    "{}, {}**'in Başını Balıq Dolu Bir Qaba Soxdu??**",
    "{}, {}**'in Üzünə Tort Tulladı!??**",
    "{}, {}**'in Üzünə Qəhvə Töktü!??**",
    "{}, {}**'in Üzünə 150 Manat Tulladı!??**",
    "{}, {}**'in Üzünə Çay Töktü!??**",
    "{}, {}**'in Üzünə Su Töktü!??**",
    "{}, {}**'İçin Aldığı Hədiyyəni Parçaladı!??**",
    "{}, {}**'in Üzünə 200 Manat Tulladı!??**",
    "{}, {}**'in Üzünə Kola Töktü!??**",
    "{}, {}**'ə Köhnə TV Tulladı!??**",
    "{}, {}**'in Qəlbini Qırdı!??**",    
    "{}, {}**'in Üzünə 1 Manat Tulladı!??**",
    "{}, {}**'in Üzünə 5 Manat Tulladı!??**",
    "{}, {}**'in Üzünə 10 Manat Tulladı!??**",
    "{}, {}**'in Üzünə 20 Manat Tulladı!??**",
    "{}, {}**'in Üzünə 50 Manat Tulladı!??**",
    "{}, {}**'in Üzünə 100 Manat Tulladı!??**",
    "{}, {}**'in Üzünə 150 Manat Tulladı!??**",
    "{}, {}**'in Üzünə 200 Manat Tulladı!??**",
    "{}, {}**'in Üzünə Bira Töktü!??**",
    "{}, {}**'in Üzünə Sillə Atdı!??**",
    "{}, {}**'in Başından Öpdü!??**",
    "{}, {}**'ə Çiçək Verdi??**",
    "{}, {}**'ə Su Tulladı! Fen Şərt Oldu??!**",
    "{}, {}**Al Bu 200-ü, Bu Gün Evə Tez Get??!**",
    "{}, {}**'ə Tapança Çəkdi! Sən də Boş Deyilsən Yəqin??!**",
    "{}, {}**'ə Adaptor Tulladı! Elektrik Saçırsan Bebeğim?⚡️**",
    "{}, {}**'ə Kitab Tulladı! Al Bu Kitabı Bir Az Oxu Ağıllan??!**",
    "{}, {}**'ə Lüğət Tulladı! Danışmağı Bilmürsən Bəyəm??!**",
    "{}, {}**'ə Çiyələk Tulladı! Al Ye Bunu??!**",
    "{}, {}**'ə Güzgü Tulladı! Bir Güzgüyə Bax Da Camaatın Gözü-Könlü Açılsın???**",
    "{}, {}**'ə Xalta Tulladı! Lazım Olar Taxarsan??!**",
    "{}, {}**'ə Çiçək Tulladı! Evlənmə Yaşın Gəlib??!**",
    "{}, {}**'ə Şalvar Tulladı! Bizdə Unutmusan??!**",
    "{}, {}**'ə Keleş Tulladı! Kürtlük Damarınız Tutdu Da-da-da-da??!**",
    "{}, {}**'ə Erosun Oxunu Atdı! Deyəsən Sənə Aşiqdir (çaktırma)??!**",
        "{}, {}**'ə Arı Yuvası Tulladı! Tez qaç, arılar gəlirrr???!**",
    "{}, {}**'ə Tərəzi Tulladı! Çəkinə görə hərəkət et aslanım??!**",
    "{}, {}**'ə Tərəzi Tulladı! Oha, çox çəkili sən ki??!**",
    "{}, {}**'ə Çanta Tulladı! Məktəbə get, oxu adam ol??!**",
    "{}, {}**'ə Premium Tulladı! Sənə Premium almaq şərtdir??!**",
    "{}, {}**'ə Domestos Tulladı! Super güclərin var artıq??!**",
    "{}, {}**'in Yanağından Öpdü??**",
    "{}, {}**'nin üzərinə benzin tökdü və od vurdu!** ??",
    "{}, {}**'nin başını balıq dolu qaba soxdu!** ??",
    "{}, {}**'nin üzünə tort tulladı! ??**",
    "{}, {}**'nin üzünə bir fincan qəhvə tökdü! **☕️",
    "{}, {}**'nin üzünə 150 $ tulladı!** ??",
    "{}, {}**'nin üzünə bir dəmkeş çay tökdü!** ??",
    "{}, {}**'nin üzünə bir stəkan su tökdü** ??",
    "{}, {}** üçün aldığı hədiyyəni parçaladı! **??",
    "{}, {}**'nin üzünə 200 $ tulladı!**??",
    "{}, {}**'nin üzünə bir şüşə kola tökdü! **??",
    "{}, {}**'nin üzərinə köhnə TV tulladı!** ??",
    "{}, {}**'nin qəlbini qırdı!**??",
    "{}, {}**'yə çiçək verdi **??",
    "{}, {}**'nin yanağından öpdü ??**",
    "{}, {}**'nin internetinin kabelini qopardı** ??",
    "{}, {}**'nin layihə tapşırığını cırdı!**??",
    "{}, {}**'nin pəncərəsinə daş atdı! **??",
    "{}, {}**'nin ağzına tualet başmağı ilə vurdu **??",
    "{}, {}**'nin başına yumşaq ev başmağı tulladı**??", 
    "{}, {}**'in burnuna ləbləbi tıxadı** ??",
    "{}, {}**'in dişini qırdı** ??",
    "{}, {}**'in maşınının təkərini partlatdı** ??",
    "{}, {}**'in ciyərini çıxarıb pişiklərə verdi **??",
    "{}, {}**'in qolunu çimdiklədi** ??",
    "{}, {}**'in saçlarına saqqız yapışdırdı** ??",
    "{}, {}**-ni Saturna qaçırdı** ??",
    "{}, {}**'in saçlarına ulduz taxdı** ??",
    "{}, {}**-ni Everestin zirvəsindən aşağı atdı** ??",
    "{}, {}**-yə Qız Qalasında çay qonaqlığı verdi** ??",
    "{}, {}**-ni valsa dəvət etdi**????",
]

sarkilar = (
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Müslüm Gürses - Ayrılık**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**İsmail YK - Allah Belanı Versin**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Güllü - Unut Gitsin**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Ceza - Holocaust**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**İbrahim Tatlıses - Mutlu Ol Yeter**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**İbrahim Tatlıses - Mavi Mavi**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Mahsun Kırmızıgül - Beşminare**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Halay - Delilo**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Derya Uluğ - Okyanus**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**İntizar - Bu Senede Kahpelik Moda**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Ahmet Kaya - Arka Mahalle**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Hirai Zerdüş - Mavi**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Hirai Zerdüş - Sevgilim**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Taladro - Dem**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Cem Karaca - Ben Ekmeğimi Böldüm de Yedim**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**İbrahim Erkal - Gönül**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Tripkolic - Gözlerinin Yeşilini Özledim**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Dilber Ay - Zorunda mıyım**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**İbrahim Tatlıses - Aramam**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Kıraç - Yalnızlığın Kapıları**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Ahmet Kaya - Bu Yalnızlık Benim**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Rei - Ah Canım Sevgilim**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**İbrahim Erkal - Çare Gelmez**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Bayhan - Tiryakinim**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Ali Kınık - Ben Seni Severken Çocuk Gibiyim**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Yıldız Tilbe - Yürü Anca Gidersin**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Yıldız Tilbe - Şarkıların Şarkısı**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**İntizar - Uykum Firari**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Hadise - Aşk Kaç Beden Giyer**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Berk Baysal - Zamanla Geçer**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Ahmet Kaya - Yakamoz**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Tarkan - Kuzu Kuzu**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Hirai Zerdüş - Sende Beni Sevdin mi?**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Taladro - Deniz Kızı**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Ankaralı Yasemin - Çıldıralım**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Davut Güloğlu - Nurcanım**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Nalan - Acemi Balık**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Mustafa Sandal - Aşka Yürek Gerek**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**İbrahim Tatlıses - Leylim Ley**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Nil İpek - Son Mektup**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Blok3 - Affetmem**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Blok3 - Vur**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Mustafa Yıldızdoğan - Ölür müydün?**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**İntizar - Ihlamurlar Altında**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Zara - Seni Yazdım Kalbime**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Zara - Beni Unutma**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Yıldız Tilbe - Emi**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Ebru Yaşar - Yoksun**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Burak Bulut - Cano**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Sura İskenderli - Dinle**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Nahide Babashlı - Söz Verdim**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Deniz Toprak - Bilmeden Oldu**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Mustafa Ceceli - Gün Ağarmadan**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Semicenk - Kader Sağolsun**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Semicenk - Batık Gemi**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Kazım Koyuncu - Hayde**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Kazım Koyuncu - Koyverdin Gittin**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Dilber Ay - Zoruna mı Gitti Gardaş**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**İbrahim Tatlıses - Ayağında Kundura**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Gazapizm - Süzülerek**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Sezen Aksu - İki Gözüm**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Sezen Aksu - Herkes Yaralı**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Celal Yarıcı - Dışarda Mevsim Baharmış**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Celal Yarıcı - Seni Sevmeyen Ölsün**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Sinan Akçıl - Bir Zamanlar Deli Gönlüm**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Mustafa Ceceli - Maşallah**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Sezen Aksu - Tükeneceğiz**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Gülnare - Bir Yari Var**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Merve Özbey - Haram**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Onurcan Özcan - Yaramızda Kalsın**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Ahmet Kaya - Söyle**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Ahmet Kaya - Beni Vur**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Mustafa Ceceli - Sevgilim**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Ahmet Kaya - Kum Gibi**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Cem Karaca - Dağlar Dağlar**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Emircan İğrek - Müzik Kutusu**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Tripkolic - Koyu Kahverengi**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Selda Bağcan - Sivasın Yollarına**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Tarkan - Öp**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Manga - Cevapsız Sorular**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Müslüm Gürses - Nilüfer**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Müslüm Gürses - Yıllar Utansın**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Hakkı Bulut - Kıskanıyorum**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Emircan İğrek - Can Dostum**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Mabel Matiz - Sultan Süleyman**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Mabel Matiz - Antidepresan**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Ümit Besen - Nikah Masası**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Mor Ve Ötesi - Bir Derdim Var**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Seksendört - Ölürüm Hasretinle**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Model - Pembe Mezarlık**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Ahmet Kaya - Metrisin Önü**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Hirai Zerdüş - Papatya**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Belkıs Akkale - Dağlar Seni Delik Delik Delerim**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Sıla - Boş Yere**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**İzzet Altınmeşe - Maden Dağı**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Neşet Ertaş - Gönül Dağı**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Uygar Doğanay - Duydum Bir Oğlun Olmuş**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Şehinşah - Nabız**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Neşet Ertaş - Ah Yalan Dünya**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Gazapizm - Heyecanı Yok**",
        "{},\n\n {}, üçün mahnı məsləhət gördü :\n\n**Mehmet Akça - Bakma Doktor Yarama**",
)

sarki1 = [ 
        "Bəsdir də, sahibimə niyə mahnı məsləhət görüm ki? 😂",
        "Sahibimə mahnı məsləhət görmürəm, o onsuz da nə dinləyəcəyini yaxşı bilir 🥳",
]
sarki2 = [ 
        "Öz-özümə mahnı məsləhət görə bilmərəm, mən botam 😁",
        "Mən mahnı dinləmirəm, mən botam canım ❤️ ",
]

dontslapme = [
    "**Ayıbdır axı, məni niyə sillələməyə çalışırsan?** 🥺",
    "😳😳",
    "**Mən bunu etməyəcəm** 😊",
    "** :Dsfgasd?**",
    "**Özümü sillələtdirmərəm.** 😑"
]
dontslapown = [
    "**Sahibimi sillələyə bilmərəm :/**",
    "**Bunu çox istəyirəm amma edə bilmərəm** 😔",
    "**Zarafat edirsən yəqin :D**",
    "**Kaş ki mümkün olaydı...**"
]
